version: 2
jobs:  
  build:  
    docker:  
      - image: circleci/node:lts
    steps: 
      - checkout
      - run: 
          name: Build
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm run test
      - run:
          name: Pre-Release
          command: npm run predeploy
      - run:
          name: Release
          command: npm run deploy